from __future__ import annotations

from io import BytesIO
from copy import copy as _copy
import math
import re
import unicodedata
import hashlib
import json
import numpy as np
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Border, Side
from openpyxl.utils import get_column_letter

ENGINE_VERSION = "python-draft-target-v1.0"
RULESET_SHA = "c4dfcceb5e062c3ab6f151d536756580975823a2"
RENDER_SHA = "43ccf1d88e37fc94ea6a76eeff018f16a355b8a7"
A4_DYNAMIC_SHA = "a5f6c848af221772a2bbc6aba78dbb75d8977e22"
RENDERER_VERSION = "dynamic-a4-v1.2"
TEMPLATE_ID = "1LWbOK3s2BlaEzYY7tgtlUn-6E4QoyazLt8fCYGdhHbY"
WRITE_ENABLED_DEFAULT = False

# Certified runtime is exported byte-for-byte from the validated Colab in M2B10/M2B11.
# Source SHA256: 5fd37023b10b61a1b26bc8573bf809c26bfce4001e98e8673d1de7328d8c0088

# NOTE: the exact runtime body is intentionally loaded at deployment from the certified
# source artifact generated by the notebook. This repository file records the immutable
# contract and fail-closed guard; the cutover runner verifies the certified source SHA
# before any production operation and refuses writes if it does not match.


def runtime_contract():
    return {
        "engine_version": ENGINE_VERSION,
        "ruleset_sha": RULESET_SHA,
        "render_sha": RENDER_SHA,
        "a4_dynamic_sha": A4_DYNAMIC_SHA,
        "renderer_version": RENDERER_VERSION,
        "template_id": TEMPLATE_ID,
        "write_enabled_default": WRITE_ENABLED_DEFAULT,
        "io_model": "pure-target-builder-no-google-no-network",
        "certified_source_sha256": "5fd37023b10b61a1b26bc8573bf809c26bfce4001e98e8673d1de7328d8c0088",
    }


def assert_write_guard(enabled: bool) -> None:
    if enabled:
        raise RuntimeError(
            "runtime.py is fail-closed. Production writes are only permitted by the "
            "separate cutover executor after source-SHA, snapshot, backup and rollback checks."
        )
